<?php


namespace LaravelSimpleBases\Templates;


class ValidationTemplate extends BaseTemplate
{

    protected $type = BaseTemplate::VALIDATION_TYPE;
    protected $template = '<?php


namespace App\Http\Validations\v1;


use Illuminate\Http\Request;
use LaravelSimpleBases\Http\Validations\BaseValidation;

class __CLASS__Validation extends BaseValidation
{

    public function validate(Request $request, $method)
    {

        $this->fieldsCreate = [     
            //Your validations here       
        ];

        parent::validate($request, $method); // TODO: Change the autogenerated stub
    }

}';

    public static function instance()
    {
        return new ValidationTemplate();
    }

}